//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWEB.ServiceReferenceUsuariosss {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsuariosss.ILoginSVC")]
    public interface ILoginSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginSVC/ValidarUsuario", ReplyAction="http://tempuri.org/ILoginSVC/ValidarUsuarioResponse")]
        bool ValidarUsuario(string usr, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginSVC/ValidarUsuario", ReplyAction="http://tempuri.org/ILoginSVC/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usr, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginSVC/NombreUSuario", ReplyAction="http://tempuri.org/ILoginSVC/NombreUSuarioResponse")]
        string NombreUSuario(string usr, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginSVC/NombreUSuario", ReplyAction="http://tempuri.org/ILoginSVC/NombreUSuarioResponse")]
        System.Threading.Tasks.Task<string> NombreUSuarioAsync(string usr, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginSVCChannel : PaginaWEB.ServiceReferenceUsuariosss.ILoginSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSVCClient : System.ServiceModel.ClientBase<PaginaWEB.ServiceReferenceUsuariosss.ILoginSVC>, PaginaWEB.ServiceReferenceUsuariosss.ILoginSVC {
        
        public LoginSVCClient() {
        }
        
        public LoginSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string usr, string pass) {
            return base.Channel.ValidarUsuario(usr, pass);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usr, string pass) {
            return base.Channel.ValidarUsuarioAsync(usr, pass);
        }
        
        public string NombreUSuario(string usr, string pass) {
            return base.Channel.NombreUSuario(usr, pass);
        }
        
        public System.Threading.Tasks.Task<string> NombreUSuarioAsync(string usr, string pass) {
            return base.Channel.NombreUSuarioAsync(usr, pass);
        }
    }
}
